In [35]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
import seaborn as sns
import matplotlib.pyplot as plt

#sklearn = module qui permet le ML. On peut aussi faire l'import au fur et à mesure

In [36]:
path_to_file="D:/Profils/NLefort/Desktop/introduction_to_python_for_data_science/ML"

df=pd.read_csv(path_to_file+"/Salary_Data.csv")

df.head()

          Country  YearsExperience   Salary
0          France              1.1  39343.0
1  United-Kingdom              1.3  46205.0
2          France              1.5  37731.0
3          France              2.0  43525.0
4         Germany              2.2  39891.0

In [37]:
print(df.shape)
#30 lignes, 3 colonnes

(30, 3)

In [ ]:
print(df.describe(include="all")) #on prend toutes les variables y-compris pas numériques

       Country  YearsExperience         Salary
count       30        30.000000      30.000000
unique       3              NaN            NaN
top     France              NaN            NaN
freq        12              NaN            NaN
mean       NaN         5.313333   76003.000000
std        NaN         2.837888   27414.429785
min        NaN         1.100000   37731.000000
25%        NaN         3.200000   56720.750000
50%        NaN         4.700000   65237.000000
75%        NaN         7.700000  100544.750000
max        NaN        10.500000  122391.000000

# Etape 3 : Feagure/traget split

In [39]:
#je veux prédire le salaire
#mes variables explicatives sont les pays et les années d'expérience
#Je veux toutes les lignes et toutes les colonnes.
#soit je lis [:,0:4] --> en allant de gauche à droite. ou alors [:,:-1] pour dire que je lis de droite à gauche en incluant toutes les colonnes

features_list = ["Country","YearsExperience"]
X=df.loc[:,features_list]
y=df.loc[:,"Salary"]

# Etape 4

In [40]:
#train_test_split !
#test_size = entre 20% et 30% de mes données vont aller dans le test set
#random state = moyen pour fixer la méthode de choix aléatoires.
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

x_train.head()

           Country  YearsExperience
27  United-Kingdom              9.6
11  United-Kingdom              4.0
17  United-Kingdom              5.3
22          France              7.9
5   United-Kingdom              2.9

In [41]:
# notanumber
# gestion des valeurs manquantes
# créer des instances de classes = je dis que ma stratégie est de remplacer par "médiane"
# une classe commence par une lettre en MAJ, soit SimpleImputer = classe
# une fonction est en min, comme imputer

imputer=SimpleImputer(strategy="median")
imputer

SimpleImputer(strategy='median')

In [ ]:

# je transforme mes valeurs mes valeurs manquantes
imputer.fit_transform(x_train.iloc[:,1:])

array([[ 9.6],
       [ 4. ],
       [ 5.3],
       [ 7.9],
       [ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [43]:
x_train.iloc[:,1:]=imputer.fit_transform(x_train.iloc[:,1:])
x_train.head()
#mes valeurs NaN sont remplacés par la médiane

           Country  YearsExperience
27  United-Kingdom              9.6
11  United-Kingdom              4.0
17  United-Kingdom              5.3
22          France              7.9
5   United-Kingdom              2.9

In [44]:
#Scaling & encoding
# créer un mini pipeline - mes données passent d'abord par sklearn puis encodeur
# je défini numeric fetaure = liste d'index de colonnes. j'ai des valeurs numériques dans colonnes 14 et 2

numeric_features=[1]
numeric_transformer= StandardScaler()

#pour mes variables catégorielles
categorical_features = [0]
categorical_transformer = OneHotEncoder ()

#le fait de mettre ma classe (par exemple, StandardScaler() sans rien entre les () = j'applique les paramètres par défaut à ma classe)

#création pipeline pré-processing =column transformer
#je transforme mes colonnes en 2 fonctionnalités. fonctionnalité catégorielle et fonctionnalité numérique.
#ces 2 transformers prennent la forme de tupples en fonction du nb de transformer que l'on aura.
feature_encoder = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features),
         #ce que prend le tupple = peut prendre n'importe quel nom, nommer le transformer auquel cela correspond, sur quelle colonne cela s'applique
        ('num', numeric_transformer, numeric_features)
    ]
)

#il faut que j'assigne sur x_train

x_train=feature_encoder.fit_transform(x_train)
x_train

array([[ 0.        ,  0.        ,  1.        ,  1.75832984],
       [ 0.        ,  0.        ,  1.        , -0.40973925],
       [ 0.        ,  0.        ,  1.        ,  0.09356251],
       [ 1.        ,  0.        ,  0.        ,  1.10016601],
       [ 0.        ,  0.        ,  1.        , -0.83560996],
       [ 0.        ,  0.        ,  1.        ,  0.01613147],
       [ 0.        ,  1.        ,  0.        , -0.7194634 ],
       [ 1.        ,  0.        ,  0.        , -0.21616165],
       [ 1.        ,  0.        ,  0.        ,  1.21631257],
       [ 0.        ,  0.        ,  1.        ,  0.6742953 ],
       [ 0.        ,  0.        ,  1.        , -1.45505827],
       [ 1.        ,  0.        ,  0.        ,  2.10676952],
       [ 0.        ,  0.        ,  1.        , -0.79689444],
       [ 0.        ,  1.        ,  0.        , -1.1066186 ],
       [ 1.        ,  0.        ,  0.        ,  0.32585562],
       [ 0.        ,  0.        ,  1.        ,  0.36457114],
       [ 0.        ,  1.        ,  0.        , -0.52588581],
       [ 0.        ,  1.        ,  0.        , -0.7194634 ],
       [ 0.        ,  1.        ,  0.        ,  1.52603672],
       [ 1.        ,  0.        ,  0.        , -1.18404964],
       [ 1.        ,  0.        ,  0.        , -1.53248931],
       [ 0.        ,  0.        ,  1.        ,  0.79044186],
       [ 0.        ,  1.        ,  0.        , -0.06129957],
       [ 1.        ,  0.        ,  0.        , -0.40973925]])

In [45]:
#j'ai bien une nouvelle matrice avec mes nouvelles valeurs

• OneHotEncoder
Transforme mes variables catégorielles en variables nominales

• standard scaler
j'ai appliquer la même échelle à l'ensembe de mes valeurs numériques et appliquant un z-score
j'ai normalisé chacune des colonnes
mes valeurs sont donc comparables

In [46]:
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [47]:
#y encoding
label_encoder=LabelEncoder()

y_train=y_train.copy()
y_train=label_encoder.fit_transform(y_train)

y_train

array([21,  5, 15, 19,  6, 12, 11, 10, 22, 16,  3, 23,  9,  1, 14, 17,  8,
        4, 20,  2,  0, 18, 13,  7], dtype=int64)

In [48]:
####### TRAINING ######

In [49]:
x_test

           Country  YearsExperience
2           France              1.5
28          France             10.3
13          France              4.1
10  United-Kingdom              3.9
26  United-Kingdom              9.5
24          France              8.7

In [50]:
x_train

array([[ 0.        ,  0.        ,  1.        ,  1.75832984],
       [ 0.        ,  0.        ,  1.        , -0.40973925],
       [ 0.        ,  0.        ,  1.        ,  0.09356251],
       [ 1.        ,  0.        ,  0.        ,  1.10016601],
       [ 0.        ,  0.        ,  1.        , -0.83560996],
       [ 0.        ,  0.        ,  1.        ,  0.01613147],
       [ 0.        ,  1.        ,  0.        , -0.7194634 ],
       [ 1.        ,  0.        ,  0.        , -0.21616165],
       [ 1.        ,  0.        ,  0.        ,  1.21631257],
       [ 0.        ,  0.        ,  1.        ,  0.6742953 ],
       [ 0.        ,  0.        ,  1.        , -1.45505827],
       [ 1.        ,  0.        ,  0.        ,  2.10676952],
       [ 0.        ,  0.        ,  1.        , -0.79689444],
       [ 0.        ,  1.        ,  0.        , -1.1066186 ],
       [ 1.        ,  0.        ,  0.        ,  0.32585562],
       [ 0.        ,  0.        ,  1.        ,  0.36457114],
       [ 0.        ,  1.        ,  0.        , -0.52588581],
       [ 0.        ,  1.        ,  0.        , -0.7194634 ],
       [ 0.        ,  1.        ,  0.        ,  1.52603672],
       [ 1.        ,  0.        ,  0.        , -1.18404964],
       [ 1.        ,  0.        ,  0.        , -1.53248931],
       [ 0.        ,  0.        ,  1.        ,  0.79044186],
       [ 0.        ,  1.        ,  0.        , -0.06129957],
       [ 1.        ,  0.        ,  0.        , -0.40973925]])

In [51]:
#valeurs manquantes
x_test.iloc[:,1:]= imputer.transform(x_test.iloc[:,1:])
#transform et pas fit transform car déjà fait sur x_train

In [52]:
#encodong &scaling
x_test=feature_encoder.transform(x_test)
x_test

array([[ 1.        ,  0.        ,  0.        , -1.37762723],
       [ 1.        ,  0.        ,  0.        ,  2.02933848],
       [ 1.        ,  0.        ,  0.        , -0.37102373],
       [ 0.        ,  0.        ,  1.        , -0.44845477],
       [ 0.        ,  0.        ,  1.        ,  1.71961432],
       [ 1.        ,  0.        ,  0.        ,  1.40989017]])

In [53]:
y_test=y_test.copy()

In [54]:
#y_test preprocessing
label_encoder=LabelEncoder()

y_test=y_test.copy()
y_test=label_encoder.fit_transform(y_test)

y_test

array([0, 5, 1, 2, 4, 3], dtype=int64)

In [58]:
# Train model
print("Train model...")
regressor = LinearRegression()
regressor.fit(x_train, y_train) # This steps is the actual training !
print("...Done.")

Train model...
...Done.

In [59]:
# Predictions on training set
print("Predictions on training set...")
y_train_pred = regressor.predict(x_train)
print("...Done.")
print(y_train_pred[:5]) # print first 5 rows (not using iloc since now y_train became a numpy array)
print()

Predictions on training set...
...Done.
[23.6656981   9.36549557 12.68518544 18.22173813  6.55652721]

algorithme regression linéaire