In [2]:
import pandas as pd

In [5]:
#même nombre d'items dans chacune des listes
pd.DataFrame({
    "bike":[10,20,5,3,8],
    "bus":[30,25,13,9,6],
    "car":[80,13,14,40,9]
})

   bike  bus  car
0    10   30   80
1    20   25   13
2     5   13   14
3     3    9   40
4     8    6    9

In [6]:
#puis je peux mettre mon data frame dans une variable

df=pd.DataFrame({
        "bike":[10,20,5,3,8],
        "bus":[30,25,13,9,6],
        "car":[80,13,14,40,9]
    })
df

   bike  bus  car
0    10   30   80
1    20   25   13
2     5   13   14
3     3    9   40
4     8    6    9

In [7]:
df.head(3)
#je veux afficher les 3 premières lignes. // par défaut il affiche les 5

   bike  bus  car
0    10   30   80
1    20   25   13
2     5   13   14

In [8]:
#en stat on essaye de comprendre ce qu'il se passe
#on veut la dist moy parcourue en vélo
df.mean()

bike     9.2
bus     16.6
car     31.2
dtype: float64

In [ ]:
#comme ça j'ai pour tout le monde

In [10]:
#écart-type
df.std()

bike     6.610598
bus     10.406729
car     29.911536
dtype: float64

In [11]:
df.median()

bike     8.0
bus     13.0
car     14.0
dtype: float64

In [12]:
df.describe()

            bike        bus        car
count   5.000000   5.000000   5.000000
mean    9.200000  16.600000  31.200000
std     6.610598  10.406729  29.911536
min     3.000000   6.000000   9.000000
25%     5.000000   9.000000  13.000000
50%     8.000000  13.000000  14.000000
75%    10.000000  25.000000  40.000000
max    20.000000  30.000000  80.000000

In [14]:
#je veux sélectionner la colonne bus
#méthodes iloc = [ligne data frame que je veux sélectionne, index de colonne]
df.iloc[0,1]

30

In [16]:
#je veux les 3-4premières
#[0:4 - 1e à 5e lignes non inclus]
df.iloc [0:4,1:3]

   bus  car
0   30   80
1   25   13
2   13   14
3    9   40

In [17]:
#qd je veux toutes les lignes et à partir de la 2e colonne
df.iloc[:,1:]

   bus  car
0   30   80
1   25   13
2   13   14
3    9   40
4    6    9

In [22]:
#je veux colonne 1 et 3, j'insère une liste - du coup j'ai fait sauter car
df.iloc[:,[0,2]]

   bike  car
0    10   80
1    20   13
2     5   14
3     3   40
4     8    9

In [23]:
#LOC- au lieu d'avoir les index j'ai les noms des colonnes
df.loc[:,["bike","car"]]

   bike  car
0    10   80
1    20   13
2     5   14
3     3   40
4     8    9

In [24]:
#je sélectionne 1 colonne, façon dictionnaire, mais moins courante
df["bike"]

0    10
1    20
2     5
3     3
4     8
Name: bike, dtype: int64