In [5]:
path_to_file="D:/Profils/NLefort/Desktop/introduction_to_python_for_data_science/pandas_trianing"

import pandas as pd

data=pd.read_csv(path_to_file+"/covid-19.csv")


data.head()

,Unnamed: 0,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018,continentExp
0,1257,2020-04-23,23,4,2020,933,264,Belgium,BE,BEL,11422068.0,Europe
1,1258,2020-04-22,22,4,2020,973,170,Belgium,BE,BEL,11422068.0,Europe
2,1259,2020-04-21,21,4,2020,1487,145,Belgium,BE,BEL,11422068.0,Europe
3,1260,2020-04-20,20,4,2020,1313,230,Belgium,BE,BEL,11422068.0,Europe
4,1261,2020-04-19,19,4,2020,1045,290,Belgium,BE,BEL,11422068.0,Europe

In [6]:
#unnamed : 0 n'est pas utile
#je veux la supprimer
data.iloc[:,1:]

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018,continentExp
0,2020-04-23,23,4,2020,933,264,Belgium,BE,BEL,11422068.0,Europe
1,2020-04-22,22,4,2020,973,170,Belgium,BE,BEL,11422068.0,Europe
2,2020-04-21,21,4,2020,1487,145,Belgium,BE,BEL,11422068.0,Europe
3,2020-04-20,20,4,2020,1313,230,Belgium,BE,BEL,11422068.0,Europe
4,2020-04-19,19,4,2020,1045,290,Belgium,BE,BEL,11422068.0,Europe
...,...,...,...,...,...,...,...,...,...,...,...
685,2020-01-04,4,1,2020,0,0,United_States_of_America,US,USA,327167434.0,America
686,2020-01-03,3,1,2020,0,0,United_States_of_America,US,USA,327167434.0,America
687,2020-01-02,2,1,2020,0,0,United_States_of_America,US,USA,327167434.0,America
688,2020-01-01,1,1,2020,0,0,United_States_of_America,US,USA,327167434.0,America
689,2019-12-31,31,12,2019,0,0,United_States_of_America,US,USA,327167434.0,America

In [7]:
# je stocke cela dans une variable
data = data.iloc[:,1:]
data.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2018,continentExp
0,2020-04-23,23,4,2020,933,264,Belgium,BE,BEL,11422068.0,Europe
1,2020-04-22,22,4,2020,973,170,Belgium,BE,BEL,11422068.0,Europe
2,2020-04-21,21,4,2020,1487,145,Belgium,BE,BEL,11422068.0,Europe
3,2020-04-20,20,4,2020,1313,230,Belgium,BE,BEL,11422068.0,Europe
4,2020-04-19,19,4,2020,1045,290,Belgium,BE,BEL,11422068.0,Europe

In [ ]:
#iloc = index location. je spécifie quelle ligne/colonne je veux capturer dans ma BDD
#iloc[:,1:] - avec à gauche ":" spécifie la ligne et à droite "1:" indique la colonne
# ":" means all the raws. we want all the raws in our dataset 
#"1:" je veux capturer la colonne 1, jusqu'à la fin de cette colonne ":"

In [8]:
data.loc[:,"year"]
#pas toujours facile de jouer avec l'Index
# je peux aller chercher le nom de ma colonne
#je veux toutes les lignes; et le nom de ma colonne
#si je veux plusieurs colonnes

0      2020
1      2020
2      2020
3      2020
4      2020
       ...
685    2020
686    2020
687    2020
688    2020
689    2019
Name: year, Length: 690, dtype: int64

In [9]:
#si je veux plusieurs colonnes
data.loc[:,["year", "cases", "deaths", "countriesAndTerritories"]]

     year  cases  deaths   countriesAndTerritories
0    2020    933     264                   Belgium
1    2020    973     170                   Belgium
2    2020   1487     145                   Belgium
3    2020   1313     230                   Belgium
4    2020   1045     290                   Belgium
..    ...    ...     ...                       ...
685  2020      0       0  United_States_of_America
686  2020      0       0  United_States_of_America
687  2020      0       0  United_States_of_America
688  2020      0       0  United_States_of_America
689  2019      0       0  United_States_of_America

[690 rows x 4 columns]

In [11]:
#si on veut plusieurs colonnes, il est préconisé de faire ainsi
columns= ["year", "cases", "deaths", "countriesAndTerritories"]
data.loc[:, columns]

     year  cases  deaths   countriesAndTerritories
0    2020    933     264                   Belgium
1    2020    973     170                   Belgium
2    2020   1487     145                   Belgium
3    2020   1313     230                   Belgium
4    2020   1045     290                   Belgium
..    ...    ...     ...                       ...
685  2020      0       0  United_States_of_America
686  2020      0       0  United_States_of_America
687  2020      0       0  United_States_of_America
688  2020      0       0  United_States_of_America
689  2019      0       0  United_States_of_America

[690 rows x 4 columns]