# Plan your trip

In [12]:
# Bibliothèques utiles
import pandas as pd
import asyncio
import os
from dotenv import load_dotenv
os.makedirs("data", exist_ok=True)
print(" Environnement prêt.")

from warnings import filterwarnings
filterwarnings("ignore")
from IPython.display import IFrame

 Environnement prêt.

## 1 - Géocodage des villes

In [2]:
from scripts.geocodage_villes import geocode_ville, villes  # juste pour que le module soit importé

# Exécution du script complet meteo.py
%run scripts/meteo.py

# Visualiser les données géocodées
df_geo = pd.read_csv("data/geocode_villes.csv")
display(df_geo.head())
print(f"{len(df_geo)} villes géocodées.")

Fichier villes_meteo.csv généré

       id_ville              ville   latitude  longitude
0  fb1372c111d5  Mont Saint Michel  48.635954  -1.511460
1  b1926dc4d399         Saint Malo  48.649518  -2.026041
2  5fd0187b51b2             Bayeux  49.276462  -0.702474
3  4e9b8cad09f6           Le Havre  49.493898   0.107973
4  e76e9773c33d              Rouen  49.440459   1.093966

35 villes géocodées.

## 2 - Données météo

In [3]:
from scripts.meteo import meteo_villes  # juste pour que le module soit importé

# Exécution du script complet meteo.py
%run scripts/meteo.py

# Vérification du résultat
import pandas as pd
df_meteo = pd.read_csv("data/villes_meteo.csv")
display(df_meteo.head())
print(f"Données météo récupérées pour {len(df_meteo)} villes.")

Fichier villes_meteo.csv généré

,id_ville,nom_ville,temp_moy,ressenti,humidity_moy,prob_pluie_moy,uv_moy
0,fb1372c111d5,Mont Saint Michel,9.5,7.4,78.3,570.0,0.8
1,b1926dc4d399,Saint Malo,10.4,8.4,72.7,700.0,0.7
2,5fd0187b51b2,Bayeux,8.6,6.2,80.1,633.0,0.8
3,4e9b8cad09f6,Le Havre,9.1,6.4,77.0,668.0,0.7
4,e76e9773c33d,Rouen,8.1,5.3,80.3,532.0,0.7

Données météo récupérées pour 35 villes.

## 3 - Hotels

In [4]:
from scripts.scrape_hotels import scrape_booking

# Exécution du script complet meteo.py
%run scripts/meteo.py

df_hotels = pd.read_csv("data/hotels.csv")
display(df_hotels.head(10))
print(f"{len(df_hotels)} hôtels récupérés.")

Fichier villes_meteo.csv généré

,id,id_ville,ville,nom,url,note,latitude,longitude
0,5871c9c2-9404-4068-ae8d-f05aa4a3bde5,fb1372c111d5,Mont Saint Michel,Hôtel Vert,https://www.booking.com/hotel/fr/vert.fr.html?...,"Avec une note de 8,1\r\n8,1\r\nTrès bien\r\n6 ...",48.635954,-1.511460
1,d23d3759-3ae2-4ff0-99fe-d3d165bfff3e,fb1372c111d5,Mont Saint Michel,La Mère Poulard,https://www.booking.com/hotel/fr/la-mere-poula...,"Avec une note de 7,6\r\n7,6\r\nBien \r\n3 392 ...",48.635954,-1.511460
2,15a33cda-6780-4216-9a88-591059307b93,fb1372c111d5,Mont Saint Michel,Auberge Saint Pierre,https://www.booking.com/hotel/fr/auberge-saint...,"Avec une note de 8,1\r\n8,1\r\nTrès bien\r\n1 ...",48.635954,-1.511460
3,ee61d6ab-fbfb-463c-bfe4-6f2c763d1665,b1926dc4d399,Saint Malo,Hotel des Abers,https://www.booking.com/hotel/fr/des-abers.fr....,"Avec une note de 8,8\r\n8,8\r\nSuperbe\r\n516 ...",48.649518,-2.026041
4,942cbdf7-7b16-4db0-8147-f93ef6e37d9e,b1926dc4d399,Saint Malo,Apartment Les Armateurs by Interhome,https://www.booking.com/hotel/fr/apartment-les...,"Avec une note de 8,7\r\n8,7\r\nSuperbe\r\n18 e...",48.649518,-2.026041
5,50a86065-685d-4bd9-a4ba-6da4289abb0e,b1926dc4d399,Saint Malo,Hôtel France et Chateaubriand,https://www.booking.com/hotel/fr/de-france-et-...,"Avec une note de 7,9\r\n7,9\r\nBien \r\n2 672 ...",48.649518,-2.026041
6,919e797d-db88-4137-bfb5-5f3ffca3b602,5fd0187b51b2,Bayeux,Château de Monceaux 5mn de Bayeux proche Mer,https://www.booking.com/hotel/fr/le-chateau-de...,"Avec une note de 9,5\r\n9,5\r\nExceptionnel\r\...",49.276462,-0.702474
7,8f6803bf-8986-492f-a5b5-ee0aacabb73c,5fd0187b51b2,Bayeux,B&B Nathalie,https://www.booking.com/hotel/fr/imagine-bayeu...,"Avec une note de 9,6\r\n9,6\r\nExceptionnel\r\...",49.276462,-0.702474
8,9ce04f13-90fb-4db8-b860-8fa76d823b1b,5fd0187b51b2,Bayeux,Apt duplex ou plain pied tout confort plein ce...,https://www.booking.com/hotel/fr/immolidays.fr...,"Avec une note de 8,0\r\n8,0\r\nTrès bien\r\n41...",49.276462,-0.702474
9,a8f2354e-31af-41b7-b3e6-499ef1627900,4e9b8cad09f6,Le Havre,Le Havre Superbe appartement avec grande terrasse,https://www.booking.com/hotel/fr/le-havre-supe...,"Avec une note de 7,4\r\n7,4\r\nBien \r\n9 expé...",49.493898,0.107973

105 hôtels récupérés.

## 4 - Fusions et export s3

In [5]:
from scripts.fusion_chargement_s3 import upload_to_s3

# Exécution du script complet 
%run scripts/fusion_chargement_s3.py


df_final = pd.read_csv("data/dataset_final.csv")
display(df_final.head())
print(f"Shape finale : {df_final.shape}")

 Fichiers chargés :
 - geocode: (35, 4)
 - meteo: (35, 7)
 - hotels: (105, 8)
Fichier consolidé exporté : data/dataset_final.csv
Upload réussi vers s3://projet-kayak-jedha-nlefort/final/dataset_final.csv
 Fichiers chargés :
 - geocode: (35, 4)
 - meteo: (35, 7)
 - hotels: (105, 8)
Fichier consolidé exporté : data/dataset_final.csv
Upload réussi vers s3://projet-kayak-jedha-nlefort/final/dataset_final.csv
Upload réussi vers s3://projet-kayak-jedha-nlefort/final/dataset_final.csv

,id,id_ville,ville,nom,url,note,latitude,longitude,nom_ville,temp_moy,ressenti,humidity_moy,prob_pluie_moy,uv_moy
0,5871c9c2-9404-4068-ae8d-f05aa4a3bde5,fb1372c111d5,Mont Saint Michel,Hôtel Vert,https://www.booking.com/hotel/fr/vert.fr.html?...,"Avec une note de 8,1\r\n8,1\r\nTrès bien\r\n6 ...",48.635954,-1.511460,Mont Saint Michel,9.5,7.4,78.3,570.0,0.8
1,d23d3759-3ae2-4ff0-99fe-d3d165bfff3e,fb1372c111d5,Mont Saint Michel,La Mère Poulard,https://www.booking.com/hotel/fr/la-mere-poula...,"Avec une note de 7,6\r\n7,6\r\nBien \r\n3 392 ...",48.635954,-1.511460,Mont Saint Michel,9.5,7.4,78.3,570.0,0.8
2,15a33cda-6780-4216-9a88-591059307b93,fb1372c111d5,Mont Saint Michel,Auberge Saint Pierre,https://www.booking.com/hotel/fr/auberge-saint...,"Avec une note de 8,1\r\n8,1\r\nTrès bien\r\n1 ...",48.635954,-1.511460,Mont Saint Michel,9.5,7.4,78.3,570.0,0.8
3,ee61d6ab-fbfb-463c-bfe4-6f2c763d1665,b1926dc4d399,Saint Malo,Hotel des Abers,https://www.booking.com/hotel/fr/des-abers.fr....,"Avec une note de 8,8\r\n8,8\r\nSuperbe\r\n516 ...",48.649518,-2.026041,Saint Malo,10.4,8.4,72.7,700.0,0.7
4,942cbdf7-7b16-4db0-8147-f93ef6e37d9e,b1926dc4d399,Saint Malo,Apartment Les Armateurs by Interhome,https://www.booking.com/hotel/fr/apartment-les...,"Avec une note de 8,7\r\n8,7\r\nSuperbe\r\n18 e...",48.649518,-2.026041,Saint Malo,10.4,8.4,72.7,700.0,0.7

Shape finale : (105, 14)

## 5 - Chargement SQL/RDS

In [6]:
from scripts.rds_sql import base_sql

# Exécution du script complet 
%run scripts/rds_sql.py

base_sql()
print("Chargement terminé !")

Dataset chargé : (105, 14)
Dataset chargé : (105, 14)
Connecté à l’instance RDS
Base 'hotels_db' vérifiée / créée avec succès
Connecté à la base 'hotels_db'
Données insérées avec succès
Connexion MariaDB fermée
Connecté à l’instance RDS
Base 'hotels_db' vérifiée / créée avec succès
Connecté à la base 'hotels_db'
Données insérées avec succès
Connexion MariaDB fermée
Chargement terminé !

## 6 - Génération des cartes

In [13]:
from scripts.cartes import charger_donnees, carte_meteo, carte_hotel # juste pour que le module soit importé

# Exécution du script complet
%run scripts/cartes.py

df_meteo, df_hotels = charger_donnees()

carte_meteo(df_meteo)
carte_hotel(df_hotels)
print("Cartes générées !")

# Affichage direct dans le notebook
display(IFrame("data/carte_meteo.html", width=900, height=600))
display(IFrame("data/top20_hotels.html", width=900, height=600))

Connecté à MariaDB
Connexion MariaDB fermée
Carte météo générée : data/carte_meteo.html
Carte hôtels générée : data/top20_hotels.html
Connecté à MariaDB
Connexion MariaDB fermée
Carte météo générée : data/carte_meteo.html
Carte hôtels générée : data/top20_hotels.html
Cartes générées !